### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by sfederici** [kikito/i18n.lua#25]
Hi, when I enter the following commands in the lua shell I get "nil"
> i18n=require 'i18n'
> i18n.set('welcome', 'welcome to this program')
> print(i18n.translate('welcome'))
nil
Am I doing something wrong?
Thanks in advance

**Comment by kikito** [comment]
Hi there,

I did not update the README after doing a change in the interface. You should do `i18n.set('en.welcome', 'welcome to this program')` - that's `en.welcome` instead of `welcome`. I have updated the README in order to reflect this. Thanks for reporting!
